---
title: "redlining EDA"
output: html_notebook
---
```{r}
library(tidyverse)
library(Inflation)
library(ggplot2)
```

```{r}
davidson_income_counts_2000 <- read_csv("davidson_income_counts_2000", col_types = cols(.default="d", GEO_ID="c", NAME="c"))
```


```{r}
davidson_income_counts_2010 <- read_csv("davidson_income_counts_2010", col_types = cols(.default="d", GEO_ID="c", NAME="c"))
```


```{r}
davidson_income_counts_2020 <- read_csv("davidson_income_counts_2020", col_types = cols(.default="d", GEO_ID="c", NAME="c"))
```


```{r}
davidson_income_percent_2000 <- read_csv("davidson_income_percent_2000", col_types = cols(.default="d", GEO_ID="c", NAME="c", CBSA10="c", METRO_NAME="c"))
```


```{r}
davidson_income_percent_2010 <- read_csv("davidson_income_percent_2010", col_types = cols(.default="d", GEO_ID="c", NAME="c", CBSA10="c", METRO_NAME="c"))
```


```{r}
davidson_income_percent_2020 <- read_csv("davidson_income_percent_2020", col_types = cols(.default="d", GEO_ID="c", NAME="c", CBSA10="c", METRO_NAME="c"))
```


```{r}
davidson_redlining_2000 <- read_csv("davidson_redlining_2000", col_types = cols(.default="c", HRI2000="d", INTERVAL2000="d"))
```


```{r}
davidson_redlining_2010 <- read_csv("davidson_redlining_2010", col_types = cols(.default="c", HRI2010="d", INTERVAL2010="d"))
```


```{r}
davidson_redlining_2020 <- read_csv("davidson_redlining_2020", col_types = cols(.default="c", HRI2020="d", INTERVAL2020="d"))

```

prepare income percent and count 2000 for analysis by dropping NA rows from redlining columns, removing unneeded data, columns and then pivot longer.
```{r}
percent_redline_2000 <- davidson_income_percent_2000 |>
    drop_na(METRO_NAME) |> 
    select(-c(HOUSEHOLDS, median_household_income, mean_household_income, METRO_NAME, CBSA10)) |> 
    relocate(c(HRI2000, INTERVAL2000), .before='income<$10k')
```


```{r}
pivot_percent_2000 <- percent_redline_2000 |> 
    pivot_longer(cols= c("income<$10k","income$10-$14,999","income$15-$24,999","income$25-$34,999","income$35-$49,999", "income$50-$74,999","income$75-$99,999","income$100-$149,999","income$150-$199,999","income>$200") ,names_to = "income_level", values_to = "household_pct")
```
set factor levels for to force x-axis order:
```{r}
pivot_percent_2000 |> 
    factor(income_level,levels=c("income<$10k","income$10-$14,999","income$15-$24,999","income$25-$34,999","income$35-$49,999", "income$50-$74,999","income$75-$99,999","income$100-$149,999","income$150-$199,999","income>$200"))
```


```{r}
pivot_percent_2000 |> 
    ggplot(aes(income_level, household_pct, color=INTERVAL2000))+
    geom_point(position="jitter")
```


right join to include only redlined census tracts and then plot median income vs redline index (with constrained y axis)
```{r}
davidson_income_counts_2000 |> 
    right_join(davidson_redlining_2000) |>
    mutate(median_income_inflated=median_household_income*(109.2/72.65)) |> 
    ggplot(aes(HRI2000, median_income_inflated))+
    geom_point()+
    scale_y_continuous(limits = c(0, 200000))

```
```{r}
davidson_income_counts_2010 |> 
    right_join(davidson_redlining_2010) |>
    mutate(median_income_inflated=median_household_income*(109.2/92)) |> 
    ggplot(aes(HRI2010, median_household_income))+
    geom_point()+
    scale_y_continuous(limits = c(0, 200000))

```

```{r}
davidson_income_counts_2020 |> 
    right_join(davidson_redlining_2020) |>
    ggplot(aes(HRI2020, median_household_income))+
    geom_point()+
    scale_y_continuous(limits = c(0, 200000))
```
and the same compared to mean instead of median
```{r}
davidson_income_counts_2000 |> 
    right_join(davidson_redlining_2000) |>
    ggplot(aes(HRI2000, mean_household_income))+
    geom_point()+
    scale_y_continuous(limits = c(0, 200000))
```
```{r}
davidson_income_counts_2010 |> 
    right_join(davidson_redlining_2010) |>
    ggplot(aes(HRI2010, mean_household_income))+
    geom_point()+
    scale_y_continuous(limits = c(0, 200000))
```

```{r}
davidson_income_counts_2020 |> 
    right_join(davidson_redlining_2020) |>
    ggplot(aes(HRI2020, mean_household_income))+
    geom_point()+
    scale_y_continuous(limits = c(0, 200000))
```


